"""Initial migration with MySQL compatibility

Revision ID: 2ca7381e404c
Revises: 
Create Date: 2025-08-02 21:18:41.259857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ca7381e404c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.alter_column('item', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###
