"""Add partner and message models

Revision ID: 4cf021e508c3
Revises: 2ca7381e404c
Create Date: 2025-08-02 21:28:13.968620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf021e508c3'
down_revision: Union[str, Sequence[str], None] = '2ca7381e404c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('intimacy_level', sa.Integer(), nullable=False),
    sa.Column('swearing_level', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('mbti', sa.String(length=10), nullable=True),
    sa.Column('speech_style', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_id'), 'partner', ['id'], unique=False)
    op.create_table('receivedmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receivedmessage_id'), 'receivedmessage', ['id'], unique=False)
    op.create_table('sentmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('original_message', sa.Text(), nullable=False),
    sa.Column('final_message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentmessage_id'), 'sentmessage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentmessage_id'), table_name='sentmessage')
    op.drop_table('sentmessage')
    op.drop_index(op.f('ix_receivedmessage_id'), table_name='receivedmessage')
    op.drop_table('receivedmessage')
    op.drop_index(op.f('ix_partner_id'), table_name='partner')
    op.drop_table('partner')
    # ### end Alembic commands ###
